# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/moro/C-interpreter-

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/moro/C-interpreter-

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.7.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/moro/C-interpreter-/CMakeFiles /Users/moro/C-interpreter-/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/moro/C-interpreter-/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named C_interpreter

# Build rule for target.
C_interpreter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 C_interpreter
.PHONY : C_interpreter

# fast build rule for target.
C_interpreter/fast:
	$(MAKE) -f CMakeFiles/C_interpreter.dir/build.make CMakeFiles/C_interpreter.dir/build
.PHONY : C_interpreter/fast

NFA_Constructor.o: NFA_Constructor.c.o

.PHONY : NFA_Constructor.o

# target to build an object file
NFA_Constructor.c.o:
	$(MAKE) -f CMakeFiles/C_interpreter.dir/build.make CMakeFiles/C_interpreter.dir/NFA_Constructor.c.o
.PHONY : NFA_Constructor.c.o

NFA_Constructor.i: NFA_Constructor.c.i

.PHONY : NFA_Constructor.i

# target to preprocess a source file
NFA_Constructor.c.i:
	$(MAKE) -f CMakeFiles/C_interpreter.dir/build.make CMakeFiles/C_interpreter.dir/NFA_Constructor.c.i
.PHONY : NFA_Constructor.c.i

NFA_Constructor.s: NFA_Constructor.c.s

.PHONY : NFA_Constructor.s

# target to generate assembly for a file
NFA_Constructor.c.s:
	$(MAKE) -f CMakeFiles/C_interpreter.dir/build.make CMakeFiles/C_interpreter.dir/NFA_Constructor.c.s
.PHONY : NFA_Constructor.c.s

PrettyPrinter.o: PrettyPrinter.c.o

.PHONY : PrettyPrinter.o

# target to build an object file
PrettyPrinter.c.o:
	$(MAKE) -f CMakeFiles/C_interpreter.dir/build.make CMakeFiles/C_interpreter.dir/PrettyPrinter.c.o
.PHONY : PrettyPrinter.c.o

PrettyPrinter.i: PrettyPrinter.c.i

.PHONY : PrettyPrinter.i

# target to preprocess a source file
PrettyPrinter.c.i:
	$(MAKE) -f CMakeFiles/C_interpreter.dir/build.make CMakeFiles/C_interpreter.dir/PrettyPrinter.c.i
.PHONY : PrettyPrinter.c.i

PrettyPrinter.s: PrettyPrinter.c.s

.PHONY : PrettyPrinter.s

# target to generate assembly for a file
PrettyPrinter.c.s:
	$(MAKE) -f CMakeFiles/C_interpreter.dir/build.make CMakeFiles/C_interpreter.dir/PrettyPrinter.c.s
.PHONY : PrettyPrinter.c.s

RegexParser.o: RegexParser.c.o

.PHONY : RegexParser.o

# target to build an object file
RegexParser.c.o:
	$(MAKE) -f CMakeFiles/C_interpreter.dir/build.make CMakeFiles/C_interpreter.dir/RegexParser.c.o
.PHONY : RegexParser.c.o

RegexParser.i: RegexParser.c.i

.PHONY : RegexParser.i

# target to preprocess a source file
RegexParser.c.i:
	$(MAKE) -f CMakeFiles/C_interpreter.dir/build.make CMakeFiles/C_interpreter.dir/RegexParser.c.i
.PHONY : RegexParser.c.i

RegexParser.s: RegexParser.c.s

.PHONY : RegexParser.s

# target to generate assembly for a file
RegexParser.c.s:
	$(MAKE) -f CMakeFiles/C_interpreter.dir/build.make CMakeFiles/C_interpreter.dir/RegexParser.c.s
.PHONY : RegexParser.c.s

lists.o: lists.c.o

.PHONY : lists.o

# target to build an object file
lists.c.o:
	$(MAKE) -f CMakeFiles/C_interpreter.dir/build.make CMakeFiles/C_interpreter.dir/lists.c.o
.PHONY : lists.c.o

lists.i: lists.c.i

.PHONY : lists.i

# target to preprocess a source file
lists.c.i:
	$(MAKE) -f CMakeFiles/C_interpreter.dir/build.make CMakeFiles/C_interpreter.dir/lists.c.i
.PHONY : lists.c.i

lists.s: lists.c.s

.PHONY : lists.s

# target to generate assembly for a file
lists.c.s:
	$(MAKE) -f CMakeFiles/C_interpreter.dir/build.make CMakeFiles/C_interpreter.dir/lists.c.s
.PHONY : lists.c.s

reader.o: reader.c.o

.PHONY : reader.o

# target to build an object file
reader.c.o:
	$(MAKE) -f CMakeFiles/C_interpreter.dir/build.make CMakeFiles/C_interpreter.dir/reader.c.o
.PHONY : reader.c.o

reader.i: reader.c.i

.PHONY : reader.i

# target to preprocess a source file
reader.c.i:
	$(MAKE) -f CMakeFiles/C_interpreter.dir/build.make CMakeFiles/C_interpreter.dir/reader.c.i
.PHONY : reader.c.i

reader.s: reader.c.s

.PHONY : reader.s

# target to generate assembly for a file
reader.c.s:
	$(MAKE) -f CMakeFiles/C_interpreter.dir/build.make CMakeFiles/C_interpreter.dir/reader.c.s
.PHONY : reader.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... C_interpreter"
	@echo "... NFA_Constructor.o"
	@echo "... NFA_Constructor.i"
	@echo "... NFA_Constructor.s"
	@echo "... PrettyPrinter.o"
	@echo "... PrettyPrinter.i"
	@echo "... PrettyPrinter.s"
	@echo "... RegexParser.o"
	@echo "... RegexParser.i"
	@echo "... RegexParser.s"
	@echo "... lists.o"
	@echo "... lists.i"
	@echo "... lists.s"
	@echo "... reader.o"
	@echo "... reader.i"
	@echo "... reader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

